version: 2
updates:
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 99
    allow:
      - dependency-type: all
    groups:
      ruby-deps:
        patterns:
          - "*"
